//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day_14.Properties {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day_14.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 4 DGXQJ =&gt; 5 QNMV
        ///10 WHSGM =&gt; 6 LFXWM
        ///3 XRJH, 15 FVRFC, 19 DGXQJ, 2 BZWFZ, 8 XDQG, 1 LFXWM, 6 CDRP =&gt; 1 LWKJL
        ///1 TLGRN =&gt; 5 BDPJD
        ///1 DBGK, 5 DTWF =&gt; 3 FVRFC
        ///7 NMWGH =&gt; 9 CGRFH
        ///1 TLRZ =&gt; 2 XRJH
        ///1 RGRHS =&gt; 7 WSGW
        ///1 DGXQJ, 15 PWXFD, 9 XRJH =&gt; 4 LGVS
        ///5 QHGP, 1 WHSGM =&gt; 7 DBGK
        ///1 RHKVX =&gt; 5 CDRP
        ///6 VMVJS =&gt; 5 VFVBP
        ///1 WSGW =&gt; 6 PGBK
        ///1 FXLD, 1 VMVJS =&gt; 8 PGJC
        ///4 WCWLK =&gt; 1 KCHWM
        ///11 XDQG =&gt; 2 QMVLD
        ///137 ORE =&gt; 4 KRSK
        ///4 KRSK =&gt; 5 HSCF
        ///1 KRSK =&gt; 7 XPGP
        ///4 BZWFZ, 1 TLGRN, 6 CTBV =&gt; 1 CPXLQ
        ///9 WNVTR, 3 FVRF [zbytek řetězce byl zkrácen];.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 2 VPVL, 7 FWMGM, 2 CXFTF, 11 MNCFX =&gt; 1 STKFG
        ///17 NVRVD, 3 JNWZP =&gt; 8 VPVL
        ///53 STKFG, 6 MNCFX, 46 VJHF, 81 HVMC, 68 CXFTF, 25 GNMV =&gt; 1 FUEL
        ///22 VJHF, 37 MNCFX =&gt; 5 FWMGM
        ///139 ORE =&gt; 4 NVRVD
        ///144 ORE =&gt; 7 JNWZP
        ///5 MNCFX, 7 RFSQX, 2 FWMGM, 2 VPVL, 19 CXFTF =&gt; 3 HVMC
        ///5 VJHF, 7 MNCFX, 9 VPVL, 37 CXFTF =&gt; 6 GNMV
        ///145 ORE =&gt; 6 MNCFX
        ///1 NVRVD =&gt; 8 CXFTF
        ///1 VJHF, 6 MNCFX =&gt; 4 RFSQX
        ///176 ORE =&gt; 6 VJHF.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
    }
}
