//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day_20.Properties {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day_20.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný                                F             G   R F   Q     J           N   G                                       
        ///                               A             T   T M   L     N           K   Z                                       
        ///  #############################.#############.###.#.###.#####.###########.###.#####################################  
        ///  #.#.#...#.#...#.#.#.....#.#.#.....#.........#.....#.#...#.#.......#.....#.........#...#.#...................#.#.#  
        ///  #.#.###.#.###.#.#.#####.#.#.###.## [zbytek řetězce byl zkrácen];.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný                    A               
        ///                   A               
        ///  #################.#############  
        ///  #.#...#...................#.#.#  
        ///  #.#.#.###.###.###.#########.#.#  
        ///  #.#.#.......#...#.....#.#.#...#  
        ///  #.#########.###.#####.#.#.###.#  
        ///  #.............#.#.....#.......#  
        ///  ###.###########.###.#####.#.#.#  
        ///  #.....#        A   C    #.#.#.#  
        ///  #######        S   P    #####.#  
        ///  #.#...#                 #......VT
        ///  #.#.#.#                 #.#####  
        ///  #...#.#               YN....# [zbytek řetězce byl zkrácen];.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný              Z L X W       C                 
        ///             Z P Q B       K                 
        ///  ###########.#.#.#.#######.###############  
        ///  #...#.......#.#.......#.#.......#.#.#...#  
        ///  ###.#.#.#.#.#.#.#.###.#.#.#######.#.#.###  
        ///  #.#...#.#.#...#.#.#...#...#...#.#.......#  
        ///  #.###.#######.###.###.#.###.###.#.#######  
        ///  #...#.......#.#...#...#.............#...#  
        ///  #.#########.#######.#.#######.#######.###  
        ///  #...#.#    F       R I       Z    #.#.#.#  
        ///  #.###.#    D       E C       H    #.#.#. [zbytek řetězce byl zkrácen];.
        /// </summary>
        internal static string Test2 {
            get {
                return ResourceManager.GetString("Test2", resourceCulture);
            }
        }
    }
}
