//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day_6.Properties {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day_6.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný CYP)BC6
        ///FPL)G1W
        ///6MM)5MX
        ///CXK)W4F
        ///TW9)KG3
        ///7LR)RVF
        ///9LK)MJF
        ///FZT)G7N
        ///4F5)YJH
        ///PJF)DJV
        ///JYT)3WQ
        ///839)Q21
        ///8CW)NGC
        ///564)8T3
        ///M86)3NM
        ///XSL)814
        ///MH7)LDS
        ///DKB)742
        ///FWR)NDK
        ///RFZ)B5P
        ///MLZ)YZQ
        ///3RK)FZB
        ///X46)NQ1
        ///Y64)VDS
        ///H79)LPF
        ///G4Q)HSZ
        ///76X)37N
        ///5X1)7PF
        ///YT3)8RH
        ///QPY)32L
        ///3M3)XY4
        ///Z9Z)ZP1
        ///MZ1)H8X
        ///2RY)VW7
        ///8CB)L95
        ///RQF)1NR
        ///JRX)2N9
        ///YV3)4R2
        ///XKB)MFH
        ///13H)1BW
        ///WQS)XBR
        ///WQ9)GQP
        ///HGX)7G5
        ///ZT8)7C6
        ///DHD)HSD
        ///TCX)7P7
        ///8NF)KTM
        ///FG4)V8D
        ///C49)DJK
        ///KBZ)MFF
        ///9SG)DBC
        ///YWQ)HF1
        ///Y7T)7RN
        ///6YM)BV6
        ///B41)P1W
        ///PSF)NLC
        ///9VN)W8W        /// [zbytek řetězce byl zkrácen];.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
    }
}
